<?php
/**
 * Created by PhpStorm.
 * User: yanni
 * Date: 21.11.2015
 * Time: 01:17
 */

namespace ICMS;

use PDO;
use PDO_MYSQL;


class TypeNormal extends Site {

    private $tplLink = "tpl/siteNormalEdit.tpl";
    private $header, $text, $title;

    function __construct($vID, $pID, $name, $type, $authorID, $lastAuthorID, $lastEditDate, $version, $state, $content) {
        parent::__construct($vID, $pID, $name, 0, $authorID, $lastAuthorID, $lastEditDate, $version, $state);
        $pgData = json_decode($content);
        $this->header = $pgData->header;
        $this->text = $pgData->text;
        $this->title = $name;
    }

    /**
     * Create a new Site Object
     *
     * @param $pID
     * @return Site
     */
    public static function fromPID($pID) {
        $pdo = new PDO_MYSQL();
        $res = $pdo->query("SELECT * FROM schlopolis_sites WHERE pID = :pid ORDER BY version DESC LIMIT 1", [":pid" => $pID]);
        return new TypeNormal($res->ID, $res->pID, $res->title, $res->type, $res->authorID, $res->lastEditID, $res->lastEditDate, $res->version, $res->state, $res->content);
    }

    /**
     * @return mixed
     */
    public function getHeader() {
        return $this->header;
    }

    /**
     * @return mixed
     */
    public function getText() {
        return $this->text;
    }

    /**
     * @return mixed
     */
    public function getTitle() {
        return $this->title;
    }

    /**
     * @param mixed $header
     */
    public function setHeader($header) {
        $this->header = $header;
    }

    /**
     * @param mixed $text
     */
    public function setText($text) {
        $this->text = $text;
    }

    /**
     * @param mixed $title
     */
    public function setTitle($title) {
        $this->title = $title;
    }

    /**
     * @return string
     */
    public function getTplLink() {
        return $this->tplLink;
    }

    public function asArray() {
        $parseDown = new \Parsedown();
        $parent = parent::asArray(); // TODO: Change the autogenerated stub
        $parent["header"] = $this->header;
        $parent["name"] = $this->getName();
        $parent["title"] = $this->title;
        $parent["text"] = $this->text;
        $parent["textHTML"] = $parseDown->text($this->text);
        return $parent;
    }

    /**
     * Creates a new Type Normal Site
     *
     * @param $name string
     * @param $user User
     * @return TypeNormal
     */
    public static function createNew($name, $user) {
        $pdo = new PDO_MYSQL();


        $pgDataStub = [
            "header" => "-- Hier kommt der Titel hin --",
            "title" => $name,
            "text" => "Hier kommt der __Text__ hin. `Markdown` wird hier unterstützt"
        ];

        $pgDataJSON = json_encode($pgDataStub);
        $authorID = $user->getUID();
        $lastEditID = $user->getUID();
        $lastEditDate = date("Y-m-d H:i:s");

        $res = $pdo->query("SELECT MAX(pID) as pID FROM schlopolis_sites");
        var_dump($res);
        $pID = $res->pID + 1;

        $resn = $pdo->queryMulti("INSERT INTO schlopolis_sites(pID, type, title, content, version, authorID, lastEditID, lastEditDate, state)"
            ."VALUES (:pID, 0, :title, :cnt, 1, :authorID, :lastEditID, :lastEditDate, 1)",
            [":pID" => $pID, ":title" => $name, ":cnt" => $pgDataJSON, ":authorID" => $authorID, ":lastEditID" => $lastEditID, ":lastEditDate" => $lastEditDate]);
        var_dump($resn->errorInfo());
        return Site::fromPID($pID);
    }


    /**
     * Saves changes in fields (title, infotext, date, link, type) and creates a new Entry
     * ** Note, this will become the state "For Approval"
     *
     * @param $user User
     * @return bool
     */
    public function saveAsNewVersion($user) {
        $pdo = new PDO_MYSQL();
        $authorID = $this->getAuthor()->getUID();
        $lastEditID = $user->getUID();
        $lastEditDate = date("Y-m-d H:i:s");
        $res = $pdo->query("SELECT MAX(version) as version FROM schlopolis_sites WHERE pID = :pID", [":pID" => $this->getPID()]);
        var_dump($res);
        $pID = $this->getPID();
        $version = $res->version + 1;
        $name = $this->getName();
        $text = $this->text;
        $header = $this->title;
        $content = [
            "header" => $header,
            "title" => $name,
            "text" => $text
        ];
        $contentJSON = json_encode($content);
        $res = $pdo->queryMulti("INSERT INTO schlopolis_sites(pID, type, title, content, version, authorID, lastEditID, lastEditDate, state)"
            ."VALUES (:pID, 0, :name, :cnt, :vers, :authorID, :lastEditID, :lastEditDate, 1)",
            [":pID" => $pID, ":name" => $name, ":cnt" => $contentJSON, ":authorID" => $authorID, ":lastEditID" => $lastEditID, ":lastEditDate" => $lastEditDate, ":vers" => $version]);
        var_dump($res->errorInfo());
    }

}